---
# Copyright (c) 2021 Linux Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "microservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "microservice.name" . }}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: {{ include "microservice.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: ARANGO_USER
              valueFrom:
                secretKeyRef:
                  name: arangodb
                  key: DBUserName
            - name: ARANGO_PASS
              valueFrom:
                secretKeyRef:
                  name: arangodb
                  key: DBPassword
            - name: ARANGO_HOST
              valueFrom:
                secretKeyRef:
                  name: arangodb
                  key: DBHost
            - name: ARANGO_PORT
              valueFrom:
                secretKeyRef:
                  name: arangodb
                  key: DBPort
            - name: RBAC_REPO
              valueFrom:
                secretKeyRef:
                  name: rbac
                  key: RBACRepo
            - name: RBAC_REPO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rbac
                  key: RBACRepoToken
            # URL Configuration (From Secret)
            - name: API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: github-creds
                  key: ApiBaseUrl
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: github-creds
                  key: BaseUrl
            # GitHub App Credentials (From Secret)
            - name: GITHUB_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: github-creds
                  key: AppName
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: github-creds
                  key: AppId
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-creds
                  key: ClientId
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-creds
                  key: ClientSecret
            - name: GITHUB_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: github-creds
                  key: PrivateKey
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
---